# Generated by Django 6.0.5 on 2026-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADO'), _negated=True), fields=('profissional', 'data_hora'), name='uq_agendamento_profissional_horario_ativo'),
        ),
    ]
